
    alter table if exists bookings
       drop constraint if exists FKrbue62imlg1u5r6rtmiifnuhw;

    alter table if exists bookings
       drop constraint if exists FKj806i9gf1tmgkrrgj23g0aqc0;

    alter table if exists comments 
       drop constraint if exists FKn2na60ukhs76ibtpt9burkm27;

    alter table if exists comments 
       drop constraint if exists FKkbkydvf8j8tfuego2iqxntwv2;

    alter table if exists items 
       drop constraint if exists FKe37yi0i6rmaqcqickvb1vty22;

    drop table if exists bookings cascade;

    drop table if exists comments cascade;

    drop table if exists items cascade;

    drop table if exists users cascade;

    create table bookings (
       id int8 generated by default as identity,
        booker_id int8,
        end_date timestamp,
        item_id int8,
        start_date timestamp,
        status varchar(255),
        primary key (id)
    );

    create table comments (
       id int8 generated by default as identity,
        author_id int8,
        created_date timestamp,
        item_id int8,
        text varchar(255),
        primary key (id)
    );

    create table items (
       id int8 generated by default as identity,
        available boolean,
        description varchar(255),
        name varchar(255),
        owner_id int8,
        request_id int8,
        primary key (id)
    );

    create table users (
       id int8 generated by default as identity,
        email varchar(255),
        name varchar(255),
        primary key (id)
    );

    alter table if exists users 
       add constraint UK_6dotkott2kjsp8vw4d0m25fb7 unique (email);

    alter table if exists bokings 
       add constraint FKrbue62imlg1u5r6rtmiifnuhw 
       foreign key (booker_id) 
       references users 
       on delete cascade;

    alter table if exists bokings 
       add constraint FKj806i9gf1tmgkrrgj23g0aqc0 
       foreign key (item_id) 
       references items 
       on delete cascade;

    alter table if exists comments 
       add constraint FKn2na60ukhs76ibtpt9burkm27 
       foreign key (author_id) 
       references users 
       on delete cascade;

    alter table if exists comments 
       add constraint FKkbkydvf8j8tfuego2iqxntwv2 
       foreign key (item_id) 
       references items 
       on delete cascade;

    alter table if exists items 
       add constraint FKe37yi0i6rmaqcqickvb1vty22 
       foreign key (owner_id) 
       references users 
       on delete cascade;
