version: '3.8'

services:
  db:
    image: postgres:15.3-alpine
    container_name: shareit-db
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=shareit
      - POSTGRES_USER=sharer
      - POSTGRES_PASSWORD=iamroot
#      - TZ=Europe/Samara

  server:
    build: ./server
    image: server-image
    container_name: shareit-server
    ports:
      - "9090:9090"
      - "9091:9091"
    depends_on:
      - db
    environment:
      - SPRING_DRIVER_CLASS_NAME=org.postgresql.Driver
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/shareit
      - SPRING_DATASOURCE_USERNAME=sharer
      - SPRING_DATASOURCE_PASSWORD=iamroot
#      - TZ=Europe/Samara

  gateway:
    build: ./gateway
    image: gateway-image
    container_name: shareit-gateway
    ports:
      - "8080:8080"
      - "8081:8081"
    depends_on:
      - server
    environment:
      - SHAREIT_SERVER_URL=http://server:9090
#      - TZ=Europe/Samara